export const ADD_CART='ADD_CART';
export const REMOVE_CART='REMOVE_CART';
export const INCREMENT_MENU_ITEM='INCREMENT_MENU_ITEM';
export const DECREMENT_MENU_ITEM='DECREMENT_MENU_ITEM';
export const VEG_FILTER='VEG_FILTER';
export const SEARCH_FILTER='SEARCH_FILTER';